"""Create a manual review workbook or CSV fallback for imported ham/service SMS."""

from __future__ import annotations

import argparse
import csv
from collections import Counter
from pathlib import Path

try:
    from openpyxl import Workbook
    from openpyxl.formatting.rule import FormulaRule
    from openpyxl.styles import Alignment, Font
    from openpyxl.styles import PatternFill
    from openpyxl.worksheet.datavalidation import DataValidation
except ImportError:  # pragma: no cover
    Workbook = None
    FormulaRule = None
    Alignment = None
    Font = None
    PatternFill = None
    DataValidation = None


ROOT = Path(__file__).resolve().parents[1]
INPUT_CSV = ROOT / "data" / "manual_ham_drive" / "extracted" / "manual_ham_extracted.csv"
OUT_XLSX = ROOT / "data" / "manual_ham_drive" / "extracted" / "manual_ham_review.xlsx"
FALLBACK_CSV = ROOT / "data" / "manual_ham_drive" / "extracted" / "manual_ham_review.csv"
SUMMARY_MD = ROOT / "reports" / "manual_ham_drive_summary.md"

LABELS = ["ham", "smishing", "spam", "unsure", "reject"]
STATUSES = ["needs_review", "approved", "rejected", "conflict_needs_review"]
CATEGORIES = [
    "otp_verification",
    "banking",
    "ewallet",
    "delivery",
    "telecom",
    "government",
    "account_security",
    "payment_confirmation",
    "appointment_reminder",
    "school_work_admin",
    "promo_legitimate",
    "promo_suspicious",
    "gambling_or_betting",
    "other",
    "unsure",
]

REQUIRED_INPUT_COLUMNS = [
    "manual_id",
    "source_file",
    "source_row_id",
    "message_raw",
    "message_clean",
    "provisional_label",
    "service_category",
    "institution_type",
    "country_or_region",
    "language",
    "contains_url",
    "contains_phone",
    "contains_otp",
    "contains_amount",
    "contains_account_hint",
    "extraction_status",
    "review_status",
    "reviewer_notes",
]

REVIEW_COLUMNS = [
    "manual_id",
    "message_raw",
    "message_clean",
    "raw_text_available",
    "text_privacy_status",
    "provisional_label",
    "final_label",
    "service_category",
    "institution_type",
    "review_status",
    "reviewer_notes",
    "source_file",
    "contains_url",
    "contains_phone",
    "contains_otp",
    "contains_amount",
    "contains_account_hint",
]


def load_rows(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8-sig", newline="") as fh:
        reader = csv.DictReader(fh)
        missing = [column for column in REQUIRED_INPUT_COLUMNS if column not in (reader.fieldnames or [])]
        if missing:
            raise ValueError(f"{path} is missing required columns: {', '.join(missing)}")
        rows = list(reader)
    for row in rows:
        if not row.get("final_label"):
            row["final_label"] = "unsure"
        row.setdefault("review_status", "needs_review")
        row.setdefault("reviewer_notes", "")
        row.setdefault("raw_text_available", "False")
        row.setdefault("text_privacy_status", "redacted_extracted_text")
        row.setdefault("contains_account_hint", "")
    return rows


def truthy(value: str) -> bool:
    return str(value).strip().lower() in {"true", "1", "yes", "y"}


def markdown_counts(title: str, counts: Counter) -> str:
    lines = [f"## {title}", "", "| Value | Count |", "| --- | ---: |"]
    if counts:
        lines.extend(f"| {key or '(blank)'} | {value} |" for key, value in counts.most_common())
    else:
        lines.append("| (none) | 0 |")
    return "\n".join(lines)


def write_candidate_summary(rows: list[dict[str, str]], path: Path) -> None:
    content = [
        "# Manual Ham Drive Summary",
        "",
        "Generated by `scripts/create_manual_ham_review_excel.py` before manual approval.",
        "",
        f"- Total rows: {len(rows)}",
        f"- Rows with URLs: {sum(truthy(row.get('contains_url', '')) for row in rows)}",
        f"- Rows with OTP: {sum(truthy(row.get('contains_otp', '')) for row in rows)}",
        f"- Rows with amount: {sum(truthy(row.get('contains_amount', '')) for row in rows)}",
        f"- Rows with phone: {sum(truthy(row.get('contains_phone', '')) for row in rows)}",
        "",
        "## Warning",
        "",
        "These rows are candidates only. They must be manually reviewed before being used as ham or template sources.",
        "",
        markdown_counts("Count by Provisional Label", Counter(row.get("provisional_label", "") for row in rows)),
        "",
        markdown_counts("Count by Review Status", Counter(row.get("review_status", "") for row in rows)),
        "",
        markdown_counts("Count by Service Category", Counter(row.get("service_category", "") for row in rows)),
        "",
        markdown_counts("Count by Institution Type", Counter(row.get("institution_type", "") for row in rows)),
        "",
        markdown_counts("Top Source Files", Counter(row.get("source_file", "") for row in rows)),
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(content) + "\n", encoding="utf-8")


def write_fallback(rows: list[dict[str, str]], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=REVIEW_COLUMNS)
        writer.writeheader()
        for row in rows:
            writer.writerow({column: row.get(column, "") for column in REVIEW_COLUMNS})


def add_dropdown(ws, column_letter: str, values: list[str], max_row: int) -> None:
    validation = DataValidation(type="list", formula1=f'"{",".join(values)}"', allow_blank=False)
    ws.add_data_validation(validation)
    validation.add(f"{column_letter}2:{column_letter}{max(max_row, 2)}")


def create_workbook(rows: list[dict[str, str]], path: Path) -> None:
    wb = Workbook()
    ws = wb.active
    ws.title = "review_queue"
    ws.append(REVIEW_COLUMNS)
    for row in rows:
        ws.append([row.get(column, "") for column in REVIEW_COLUMNS])

    ws.freeze_panes = "A2"
    ws.auto_filter.ref = ws.dimensions
    widths = {
        "A": 18,
        "B": 48,
        "C": 48,
        "D": 18,
        "E": 28,
        "F": 18,
        "G": 16,
        "H": 24,
        "I": 20,
        "J": 24,
        "K": 56,
        "L": 24,
    }
    for column, width in widths.items():
        ws.column_dimensions[column].width = width
    for row in ws.iter_rows():
        for cell in row:
            cell.alignment = Alignment(wrap_text=True, vertical="top")
    for cell in ws[1]:
        cell.font = Font(bold=True)

    add_dropdown(ws, "G", LABELS, len(rows) + 1)
    add_dropdown(ws, "H", CATEGORIES, len(rows) + 1)
    add_dropdown(ws, "J", STATUSES, len(rows) + 1)
    if FormulaRule is not None and PatternFill is not None:
        last_row = max(len(rows) + 1, 2)
        ws.conditional_formatting.add(
            f"A2:Q{last_row}",
            FormulaRule(
                formula=['OR($M2=TRUE,$M2="True",$P2=TRUE,$P2="True",$H2="unsure")'],
                fill=PatternFill("solid", fgColor="FFF2CC"),
            ),
        )

    label_ws = wb.create_sheet("label_guide")
    label_ws.append(["label", "meaning"])
    guides = {
        "HAM": "Use ham only if clearly legitimate/non-malicious: OTP or verification code with no suspicious action, bank transaction alert, payment confirmation, delivery status update, telecom/service advisory, government/public service notification, appointment/reminder message, or legitimate promo without suspicious demand.",
        "SMISHING": "Use smishing if the message asks the user to verify/login/update account through a link, threatens account lock/suspension, asks for OTP/password/PIN/credentials, impersonates bank/e-wallet/delivery/government, uses urgent financial/security bait, or contains suspicious link/callback instruction.",
        "SPAM": "Use spam if promotional/unwanted but not clearly phishing, including gambling/free spins/casino offers, aggressive promos, random reward offers without clear credential theft, or ads that are not clearly legitimate service messages.",
        "UNSURE": "Use unsure if unclear, cropped, incomplete, OCR-damaged, or needing another reviewer.",
        "REJECT": "Use reject if not SMS-like, non-English, too incomplete, duplicate, unsafe/private data cannot be redacted, or not useful for the thesis dataset.",
    }
    for key, value in guides.items():
        label_ws.append([key, value])
    label_ws.append([])
    label_ws.append(["Reviewer instruction", "Approve only legitimate ham rows for template extraction."])
    label_ws.append(["Template exclusion", "Rows labeled spam, smishing, unsure, or reject must NOT be used for ham template extraction."])
    label_ws.append(
        [
            "Source text note",
            "`message_raw` comes from THESIS/TEXT EXTRACTED/raw_extracted_dataset.csv when a matching record_id exists. `message_clean` comes from the cleaned/redacted source and may preserve placeholders such as <OTP>, <PHONE>, <URL>, <ACCT>, and <NAME>.",
        ]
    )
    label_ws.append(
        [
            "reviewer_notes",
            "Use this column for suspicious reason, why it is legitimate ham, why it is smishing, why it is spam, why it is unsure/rejected, OCR/extraction issues, and duplicate or overlap notes.",
        ]
    )
    label_ws.column_dimensions["A"].width = 18
    label_ws.column_dimensions["B"].width = 110

    category_ws = wb.create_sheet("category_guide")
    category_ws.append(["service_category"])
    for category in CATEGORIES:
        category_ws.append([category])
    category_ws.column_dimensions["A"].width = 28

    summary_ws = wb.create_sheet("summary")
    summary_ws.append(["field", "value"])
    summary_ws.append(["rows_in_review_queue", len(rows)])
    summary_ws.append(["approved_ham_rule", "final_label=ham and review_status=approved"])
    summary_ws.append(["synthetic_use_warning", "Synthetic ham must be tracked separately from real ham."])
    summary_ws.column_dimensions["A"].width = 28
    summary_ws.column_dimensions["B"].width = 80

    path.parent.mkdir(parents=True, exist_ok=True)
    wb.save(path)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=INPUT_CSV)
    parser.add_argument("--output", type=Path, default=OUT_XLSX)
    args = parser.parse_args()
    rows = load_rows(args.input)
    write_candidate_summary(rows, SUMMARY_MD)

    if Workbook is None:
        write_fallback(rows, FALLBACK_CSV)
        print(f"openpyxl is not available; wrote CSV fallback to {FALLBACK_CSV}")
        print(f"Wrote candidate summary to {SUMMARY_MD}")
        return

    create_workbook(rows, args.output)
    write_fallback(rows, FALLBACK_CSV)
    print(f"Wrote review workbook to {args.output}")
    print(f"Wrote CSV fallback to {FALLBACK_CSV}")
    print(f"Wrote candidate summary to {SUMMARY_MD}")


if __name__ == "__main__":
    main()
