"""Validate reviewed manual ham rows and export approved/rejected splits."""

from __future__ import annotations

import argparse
import csv
from collections import Counter
from pathlib import Path

try:
    import pandas as pd
except ImportError:  # pragma: no cover
    pd = None


ROOT = Path(__file__).resolve().parents[1]
REVIEW_XLSX = ROOT / "data" / "manual_ham_drive" / "extracted" / "manual_ham_review.xlsx"
REVIEW_CSV = ROOT / "data" / "manual_ham_drive" / "extracted" / "manual_ham_review.csv"
APPROVED_CSV = ROOT / "data" / "manual_ham_drive" / "final" / "approved_manual_ham.csv"
REJECTED_CSV = ROOT / "data" / "manual_ham_drive" / "rejected" / "rejected_manual_ham.csv"
NEEDS_REVIEW_CSV = ROOT / "data" / "manual_ham_drive" / "final" / "manual_ham_needs_review_remaining.csv"
SMISHING_FOUND_CSV = ROOT / "data" / "manual_ham_drive" / "final" / "manual_ham_smishing_found.csv"
SPAM_FOUND_CSV = ROOT / "data" / "manual_ham_drive" / "final" / "manual_ham_spam_found.csv"
SUMMARY_MD = ROOT / "reports" / "manual_ham_drive_summary.md"

REQUIRED_COLUMNS = [
    "reviewer_notes",
    "raw_text_available",
    "text_privacy_status",
    "contains_account_hint",
]


def read_review(path: Path) -> list[dict[str, str]]:
    if path.suffix.lower() == ".xlsx" and path.exists() and pd is not None:
        frame = pd.read_excel(path, sheet_name="review_queue")
        return frame.fillna("").astype(str).to_dict("records")
    csv_path = path if path.suffix.lower() == ".csv" else REVIEW_CSV
    if not csv_path.exists():
        return []
    with csv_path.open("r", encoding="utf-8-sig", newline="") as fh:
        return list(csv.DictReader(fh))


def ensure_required_columns(rows: list[dict[str, str]]) -> list[dict[str, str]]:
    for row in rows:
        for column in REQUIRED_COLUMNS:
            row.setdefault(column, "")
        row.setdefault("final_label", "")
        row.setdefault("review_status", "needs_review")
        if not row["raw_text_available"]:
            row["raw_text_available"] = "False"
        if not row["text_privacy_status"]:
            row["text_privacy_status"] = "redacted_extracted_text"
    return rows


def normalized(row: dict[str, str], column: str) -> str:
    return row.get(column, "").strip().lower()


def write_csv(path: Path, rows: list[dict[str, str]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def markdown_counts(title: str, counts: Counter) -> str:
    lines = [f"## {title}", "", "| Value | Count |", "| --- | ---: |"]
    if counts:
        lines.extend(f"| {key or '(blank)'} | {value} |" for key, value in counts.most_common())
    else:
        lines.append("| (none) | 0 |")
    return "\n".join(lines)


def truthy(value: str) -> bool:
    return str(value).strip().lower() in {"true", "1", "yes", "y"}


def write_summary(
    rows: list[dict[str, str]],
    approved: list[dict[str, str]],
    rejected: list[dict[str, str]],
    smishing: list[dict[str, str]],
    spam: list[dict[str, str]],
    needs_review: list[dict[str, str]],
) -> None:
    final_labels = Counter(normalized(row, "final_label") for row in rows)
    provisional_labels = Counter(row.get("provisional_label", "") for row in rows)
    review_statuses = Counter(row.get("review_status", "") for row in rows)
    categories = Counter(row.get("service_category", "") for row in rows)
    institutions = Counter(row.get("institution_type", "") for row in rows)
    sources = Counter(row.get("source_file", "") for row in rows)
    content = [
        "# Manual Ham Drive Summary",
        "",
        "Generated by `scripts/validate_manual_ham_review.py`.",
        "",
        f"- Total reviewed rows: {len(rows)}",
        f"- Approved ham rows: {len(approved)}",
        f"- Smishing discovered rows: {len(smishing)}",
        f"- Spam discovered rows: {len(spam)}",
        f"- Unsure rows: {final_labels.get('unsure', 0)}",
        f"- Rejected rows: {len(rejected)}",
        f"- Needs-review remaining rows: {len(needs_review)}",
        f"- Rows with URLs: {sum(truthy(row.get('contains_url', '')) for row in rows)}",
        f"- Rows with OTP: {sum(truthy(row.get('contains_otp', '')) for row in rows)}",
        f"- Rows with amount: {sum(truthy(row.get('contains_amount', '')) for row in rows)}",
        f"- Rows with phone: {sum(truthy(row.get('contains_phone', '')) for row in rows)}",
        "- `message_raw` in this workflow is raw OCR extracted text when available from the manual Drive raw extraction file.",
        "- `reviewer_notes` is preserved in exports for auditability and thesis defensibility.",
        "",
        "## Warning",
        "",
        "These rows are candidates only. They must be manually reviewed before being used as ham or template sources.",
        "",
        markdown_counts("Count by Provisional Label", provisional_labels),
        "",
        markdown_counts("Count by Review Status", review_statuses),
        "",
        markdown_counts("Count by Service Category", categories),
        "",
        markdown_counts("Count by Institution Type", institutions),
        "",
        markdown_counts("Top Source Files", sources),
    ]
    SUMMARY_MD.parent.mkdir(parents=True, exist_ok=True)
    SUMMARY_MD.write_text("\n".join(content) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--review-file", type=Path, default=REVIEW_XLSX)
    args = parser.parse_args()

    rows = ensure_required_columns(read_review(args.review_file))
    approved = [row for row in rows if normalized(row, "final_label") == "ham" and normalized(row, "review_status") == "approved"]
    smishing = [row for row in rows if normalized(row, "final_label") == "smishing"]
    spam = [row for row in rows if normalized(row, "final_label") == "spam"]
    needs_review = [
        row
        for row in rows
        if normalized(row, "final_label") == "unsure"
        or normalized(row, "review_status") in {"needs_review", "conflict_needs_review"}
    ]
    rejected = [
        row
        for row in rows
        if normalized(row, "final_label") == "reject" or normalized(row, "review_status") == "rejected"
    ]
    fieldnames = list(rows[0].keys()) if rows else REQUIRED_COLUMNS
    for column in REQUIRED_COLUMNS:
        if column not in fieldnames:
            fieldnames.append(column)
    write_csv(APPROVED_CSV, approved, fieldnames)
    write_csv(REJECTED_CSV, rejected, fieldnames)
    write_csv(NEEDS_REVIEW_CSV, needs_review, fieldnames)
    write_csv(SMISHING_FOUND_CSV, smishing, fieldnames)
    write_csv(SPAM_FOUND_CSV, spam, fieldnames)
    write_summary(rows, approved, rejected, smishing, spam, needs_review)
    print(f"Approved ham rows: {len(approved)} -> {APPROVED_CSV}")
    print(f"Rejected/manual non-approved rows: {len(rejected)} -> {REJECTED_CSV}")
    print(f"Needs-review rows: {len(needs_review)} -> {NEEDS_REVIEW_CSV}")
    print(f"Smishing rows: {len(smishing)} -> {SMISHING_FOUND_CSV}")
    print(f"Spam rows: {len(spam)} -> {SPAM_FOUND_CSV}")
    print(f"Summary: {SUMMARY_MD}")


if __name__ == "__main__":
    main()
